### ISSUE TITLE
学长可以把这个仓库贡献到awesome-se notes

### ISSUE THREAD

**Issue by WindowsXp-Beta** [shenhliu/Fuck-SJTU-ML-Exam#1]
链接：[awesome-se notes](https://github.com/SJTU-SE/awesome-se-notes)

**Comment by shenhliu** [comment]
我已经添加了机器学习的笔记，请有空的时候帮忙合并一下，麻烦了

Xinpeng Wei ***@***.***> 于2022年1月1日周六 12:51写道：

**Comment by WindowsXp-Beta** [comment]
Thx
